photo_album/config/routes.rb
Rails.application.routes.draw do
	resources :photos
	root "photos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

photo_album/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

photo_album/app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :file_location, PhotoImageUploader
	validates_presence_of :title, :date, :file_location

end

photo_album/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

photo_album/app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	# recall homepage
	def index
		@photos = Photo.all

	end

	#build up a new file
	def new
		@photo = Photo.new # 要先定義實例變數給form_for使用（預設必須提供）

	end

	# then create after build up
	def create
		@photo = Photo.new(photo_params)
		if @photo.save
			redirect_to photo_path(@photo) #新建檔案後應跳回該檔案show page

		else
			render :action => :new

		end

	end

	#show the photo info.
	def show
		@photo = Photo.find(params[:id])

	end


	# edit file
	def edit 
		@photo = Photo.find(params[:id])

	end

	# update after edit
	def update
		@photo = Photo.find(params[:id])
		if @photo.update(photo_params)
			redirect_to photo_url(@photo)

		else
			render :action => :edit

		end

	end

	#destroy an item
	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy

		redirect_to photos_url

	end

	private

	def photo_params # 定義params 讓使用者在頁面上輸入的資料可以被rails認同並更改，預設為所有資料都無法存取
		params.require(:photo).permit(:title, :date, :description, :file_location)

	end

end

photo_album/app/helpers/application_helper.rb
module ApplicationHelper
end

photo_album/app/helpers/photos_helper.rb
module PhotosHelper
end

photo_album/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

photo_album/app/views/photos/_form.html.erb
<% if @photo.errors.any? %>
	<h2>We have some errors here !!</h2>
	<ul>
		<% @photo.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>


<%= form_for @photo do |f| %>
	<%= f.label :title, "Title : " %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :date, "Date : " %>
	<%= f.text_field :date %>
	<br>
	<%= f.label :description, "Description : " %>
	<br>
	<%= f.text_area :description %>
	<br>
	<%= f.label :file_location, "File location : " %>
	<%= f.file_field :file_location %>
	<br>	
	<%= f.submit %>

<% end %>


<p><%= link_to 'BACK', photos_path %></p>

photo_album/app/views/photos/edit.html.erb
<!-- # <%= form_for @photo do |f| %>
# 	<%= f.label :title, "Title : " %>
# 	<%= f.text_field :title %>

# 	<%= f.label :date, "Date : " %>
# 	<%= f.text_field :date %>

# 	<%= f.label :description, "Description : " %>
# 	<%= f.text_area :description %>

# 	<%= f.label :file_location, "File location : " %>
# 	<%= f.text_field :file_location %>

# 	<%= f.submit 'UPDATE' %>

# <% end %> -->

<%= render :partial => "form" %>

photo_album/app/views/photos/index.html.erb
<h1 style="text-align: center;">My Albums by rails</h1>
<ul>
	<% @photos.each do |photo| %>
		<li>
			<%= photo.title %>
			<br>
			<%= link_to 'SHOW', photo_path(photo) %>
			<%= link_to 'EDIT', edit_photo_path(photo) %>
			<%= link_to 'DELETE', photo_path(photo), method: :delete, data:{
					confirm: "Are you sure you want to delete this photo ?"
				} %>			

		</li>
	<% end %>
	
</ul>

<%= link_to 'Add New Photo', new_photo_path %>

photo_album/app/views/photos/new.html.erb
<!-- # <%= form_for @photo, :url => photos_path do |f| %>   :url => photos_path告訴form_for要把東西送到哪，但不給的話就自動回傳到綁定的＠photo頁面上
# 	<%= f.label :title, "Title : " %>
# 	<%= f.text_field :title %>

# 	<%= f.label :date, "Date : " %>
# 	<%= f.text_field :date %>

# 	<%= f.label :description, "Description : " %>
# 	<%= f.text_area :description %>
	
# 	<%= f.label :file_location, "File location : " %>
# 	<%= f.text_field :file_location %>

# 	<%= f.submit "Create" %>

# <% end %> -->

<%= render :partial => "form" %>

photo_album/app/views/photos/show.html.erb
<%= @photo.title %>

<%= @photo.date %>

<%= image_tag @photo.file_location.url %>
<%= simple_format(@photo.description) %>

<p><%= link_to 'BACK', photos_path %></p>